const STORAGE='daily-food-journal-v2',base={gender:'female',age:30,height:165,weight:60,activity:1.2,goal:-400,target:2000};
const makeUser=(id,name)=>({id,name,profile:{...base},entries:{},weights:{}});
let state=JSON.parse(localStorage.getItem(STORAGE));
if(!state)state=JSON.parse(localStorage.getItem('daily-food-journal-v1'))||{profile:base,entries:{},weights:{}};
if(!state.users)state={activeUser:'user-1',users:[{id:'user-1',name:'用户 1',profile:{...base,...state.profile},entries:state.entries||{},weights:state.weights||{}},makeUser('user-2','用户 2')]};
state.users.forEach(person=>{person.exercises ||= {};person.restaurants ||= []});
const $=id=>document.getElementById(id),day=()=>{let now=new Date(),offset=now.getTimezoneOffset();return new Date(now.getTime()-offset*60000).toISOString().slice(0,10)},u=()=>state.users.find(x=>x.id===state.activeUser)||state.users[0],num=v=>Number(v)||0;
const nutritionInfo=[['鸡胸肉（生）','100g',120,23,0,2.6],['瘦牛肉（生）','100g',170,21,0,9],['五花肉（生）','100g',520,10,0,53],['猪排骨（生）','100g',270,17,0,22],['三文鱼','100g',208,20,0,13],['鸡蛋','100g',143,13,1,10],['北豆腐','100g',80,8,2,4.5],['西兰花','100g',34,3,7,0.4],['青菜','100g',15,1.5,2,0.2],['番茄','100g',18,0.9,3.9,0.2],['土豆','100g',77,2,17,0.1],['白米饭（熟）','100g',130,2.4,28,0.3],['面条（熟）','100g',138,5,25,2],['燕麦（干）','100g',389,17,66,7],['全麦面包','100g',247,13,41,4],['汉堡包（牛肉）','1 个',550,28,45,29],['炸鸡','100g',290,20,12,18],['牛肉面','1 碗',650,30,80,22],['烧鸭','100g',330,19,4,26],['烤鸭','100g',340,19,3,28],['炒面','1 份',650,18,85,25],['炒饭','1 份',700,20,95,24],['烧烤（肉串）','100g',250,20,8,16],['火锅（不含蘸料）','1 餐',650,35,45,34],['螺蛳粉','1 碗',550,15,75,20],['炸串','100g',310,14,18,20],['戚风蛋糕','100g',280,6,42,10],['千层蛋糕','100g',390,6,35,25],['珍珠奶茶（全糖）','1 杯',480,5,85,13],['纯牛奶','100ml',62,3.2,4.8,3.4],['无糖奶茶','1 杯',180,5,24,7]];
const femaleGuide=[['女性每日营养参考','一般健康 19–50 岁、非孕哺成人','能量：以个人身高、体重、活动量及目标为准；本 App 的个人目标优先。'],['蛋白质','≥0.83 g／kg 体重','例如 60kg 成人至少约 50g；增肌或高强度训练者需要个别调整。'],['脂肪','≤总能量 30%','优先不饱和脂肪；饱和脂肪＜10% 总能量，反式脂肪＜1%。'],['游离糖','＜总能量 10%','按 2,000 kcal 约＜50g；理想＜25g。'],['钠','＜2,000 mg','约等于食盐＜5g；高血压或肾脏疾病请遵医嘱。'],['钾','≥3,510 mg','主要来自蔬菜、水果、豆类及奶类；肾病患者请先咨询医生。'],['蔬菜＋水果','≥400 g','尽量多样化，果汁不等同完整水果。'],['铁','18 mg','19–50 岁有月经女性的常用参考；绝经后通常为 8mg。']];
const trim=()=>{let d=new Date();d.setMonth(d.getMonth()-18);let first=new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10);state.users.forEach(p=>['entries','weights','exercises'].forEach(k=>Object.keys(p[k]||{}).forEach(x=>{if(x<first)delete p[k][x]})))};
nutritionInfo.push(['寿司（生鱼握寿司）','100g',150,7,27,2],['三文鱼寿司卷','1 卷',320,14,48,8],['比萨（芝士）','100g',270,12,33,11],['比萨（意式腊肠）','100g',310,13,32,16],['重庆小面','1 碗',560,14,78,21],['家常炒青菜','100g',65,2,5,4],['青椒肉丝','100g',160,14,6,9],['鱼香肉丝','100g',180,13,12,10],['芹菜牛肉','100g',145,16,5,7],['水饺（猪肉白菜）','10 个',420,20,52,14],['蒸包子（肉馅）','1 个',250,11,33,8],['小笼包','6 个',360,17,42,13],['早茶虾饺','4 个',170,12,20,5],['早茶烧卖','4 个',250,14,25,11],['肠粉','1 份',330,10,53,8],['铁锅炖（鸡肉蔬菜）','1 份',620,38,48,27],['铁锅炖（排骨）','1 份',780,36,55,44],['煎饼果子','1 个',480,14,60,21],['肉夹馍','1 个',390,18,42,16],['凉皮','1 份',350,8,58,9],['烤冷面','1 份',430,13,55,18],['炸薯条','中份',340,4,45,16],['冰淇淋','100g',210,4,24,11],['蛋挞','1 个',210,4,22,12],['豆浆（无糖）','250ml',80,7,5,4],['麦当劳 薯饼（NZ）','1 份',144,1.4,12.5,9.6],['麦当劳 香肠鸡蛋麦满分（NZ）','1 个',380,23.9,24.2,20.3],['麦当劳 Massive McMuffin（NZ）','1 个',520,35.5,28,28.9],['麦当劳 Big Brekkie Beef Burger（NZ）','1 个',808,43.3,51.5,47.1],['麦当劳 热香饼配黄油糖浆（NZ）','1 份',600,9,98,18]);
nutritionInfo.push(['水盆羊肉','1 碗',520,32,35,27],['羊肉泡馍','1 碗',750,35,75,34],['油泼面','1 碗',680,16,90,28],['凉拌黄瓜','100g',55,1.5,5,3.5],['凉拌木耳','100g',70,2,10,3],['拍黄瓜','1 份',110,3,10,7],['凉拌牛肉','100g',180,22,4,9],['凉拌皮蛋豆腐','1 份',230,15,8,14],['口水鸡','100g',210,18,5,13],['炭烧牛杂','1 份',380,28,18,20],['生煎包','4 个',480,17,52,24],['锅贴','6 个',420,18,46,19],['烤羊肉串','3 串',360,27,6,24],['羊肉汤','1 碗',280,25,8,16]);
const save=()=>{trim();localStorage.setItem(STORAGE,JSON.stringify(state))},today=()=>u().entries[day()]||[],total=k=>today().reduce((s,x)=>s+num(x[k]),0),esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let editingIndex=null;
const todayExercises=()=>u().exercises[day()]||[];
function renderExercises(){let list=$('exerciseList'),items=todayExercises(),calories=items.reduce((sum,item)=>sum+num(item.calories),0);$('exerciseCalories').textContent=calories;$('exerciseEmpty').hidden=!!items.length;list.innerHTML='';items.forEach((item,index)=>list.insertAdjacentHTML('beforeend',`<article class="food card"><div class="food-icon">${item.type==='strength'||item.type==='weights'?'🏋️':'🏃'}</div><div class="food-main"><p class="food-name">${esc(item.name)}</p><p class="food-meta">${item.minutes} 分钟${item.steps?' · '+item.steps+' 步':''}${item.sets?' · '+item.sets+' 组 × '+item.reps+' 次':''}</p></div><div class="food-kcal">-${item.calories}<small> kcal</small></div><button class="delete exercise-delete" data-index="${index}">×</button></article>`));document.querySelectorAll('.exercise-delete').forEach(button=>button.onclick=()=>{u().exercises[day()].splice(button.dataset.index,1);save();render()})}
function mealIdeas(left,gap){return left<150?'今天热量空间不多：可选无糖希腊酸奶、茶叶蛋或一小碗紫菜豆腐汤。':gap>0?`还建议补约 ${gap}g 蛋白质。中式可选：清蒸鱼配青菜和半碗饭，或番茄鸡蛋豆腐汤；奥克兰常见选择：烤鸡胸沙拉、poke bowl（少酱）或 Greek yoghurt 配莓果。`:'下一餐可选：牛肉西兰花炒饭（少油）、三文鱼饭碗配沙拉，或越南鸡肉粉；饮料优先无糖茶、气泡水或 long black。'}
function editFood(index){let f=today()[index];editingIndex=index;['foodName','foodCalories','foodProtein','foodCarbs','foodFat','foodSodium'].forEach(k=>$(k).value=f[{foodName:'name',foodCalories:'calories',foodProtein:'protein',foodCarbs:'carbs',foodFat:'fat',foodSodium:'sodium'}[k]]??'');$('mealType').value=f.type;document.querySelector('#foodDialog h2').textContent='编辑餐食';$('foodDialog').showModal()}
function refreshRestaurants(){let select=$('restaurantPreset'),list=$('restaurantList');select.innerHTML='<option value="">选择已收藏的菜品</option>';list.innerHTML='';u().restaurants.forEach((r,ri)=>r.dishes.forEach((d,di)=>{select.insertAdjacentHTML('beforeend',`<option value="${ri}:${di}">${r.name} · ${d.name}（${d.calories} kcal）</option>`);list.insertAdjacentHTML('beforeend',`<div class="history-item"><span>${r.name} · ${d.name} · ${d.calories} kcal</span><button class="delete restaurant-delete" data-id="${ri}:${di}">×</button></div>`)}));document.querySelectorAll('.restaurant-delete').forEach(b=>b.onclick=()=>{let [ri,di]=b.dataset.id.split(':').map(Number),r=u().restaurants[ri];r.dishes.splice(di,1);if(!r.dishes.length)u().restaurants.splice(ri,1);save();refreshRestaurants()})}
function render(){let p=u(),cal=total('calories'),target=num(p.profile.target),left=target-cal;$('todayLabel').textContent=`${new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',weekday:'long'}).format(new Date())} · ${p.name}`;$('eatenValue').textContent=cal;$('targetValue').textContent=target;$('calorieValue').textContent=Math.max(0,left);$('proteinValue').textContent=total('protein')+'g';$('carbValue').textContent=total('carbs')+'g';$('fatValue').textContent=total('fat')+'g';$('calorieRing').style.background=`conic-gradient(var(--green) ${Math.min(100,cal/target*100)*3.6}deg,#dbe9dc 0deg)`;let list=$('foodList'),icons={早餐:'☀️',午餐:'🥗',晚餐:'🍲',加餐:'🍎',零食:'🍪'};list.innerHTML='';today().forEach((f,i)=>list.insertAdjacentHTML('beforeend',`<article class="food card"><div class="food-icon">${icons[f.type]||'🍽️'}</div><div class="food-main"><p class="food-name">${esc(f.name)}</p><p class="food-meta">${f.type} · 蛋白质 ${num(f.protein)}g${num(f.sodium)?` · 钠 ${f.sodium}mg`:''}</p></div><div class="food-kcal">${num(f.calories)}<small> kcal</small></div><button class="delete" data-index="${i}">×</button></article>`));$('emptyState').hidden=!!today().length;let protein=total('protein'),advice=cal===0?'今天还没有餐食记录。先记录一餐，建议优先从蛋白质和蔬菜开始。':left<-150?`今天已超出目标 ${Math.abs(left)} kcal。下一餐可选择蔬菜、瘦蛋白和清淡汤品。`:protein<p.profile.weight*1.2?`今天还可安排约 ${Math.max(15,Math.round(p.profile.weight*1.2-protein))}g 蛋白质，例如鸡蛋、豆腐或鱼。`:`记录得很好。还剩 ${Math.max(0,left)} kcal，下一餐保持蔬菜、蛋白质和适量主食即可。`;$('advice').innerHTML=`<p>${advice}</p>`;document.querySelectorAll('.delete').forEach(b=>b.onclick=()=>{u().entries[day()].splice(b.dataset.index,1);save();render()})}
function fillProfile(){let p=u();$('userPicker').innerHTML=state.users.map(x=>`<option value="${x.id}">${x.name}</option>`).join('');$('userPicker').value=p.id;$('userName').value=p.name;Object.entries(p.profile).forEach(([k,v])=>{let e=$(k==='target'?'calorieTarget':k);if(e)e.value=v})}
function askWeight(){let weights=u().weights||{},todayKey=day();if(!Object.prototype.hasOwnProperty.call(weights,todayKey)){$('dailyWeight').value=u().profile.weight;setTimeout(()=>{if(!Object.prototype.hasOwnProperty.call((u().weights||{}),todayKey)&&!$('weightDialog').open)$('weightDialog').showModal()},350)}}
$('addFoodButton').onclick=()=>$('foodDialog').showModal();$('profileButton').onclick=$('profileNavButton').onclick=()=>{fillProfile();$('profileDialog').showModal()};
$('userPicker').onchange=()=>{state.activeUser=$('userPicker').value;save();fillProfile();render();askWeight()};
$('profileForm').onsubmit=e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();let p=u();p.name=$('userName').value.trim()||p.name;['gender','age','height','weight','activity','goal'].forEach(k=>p.profile[k]=k==='gender'?$(k).value:num($(k).value));p.profile.target=num($('calorieTarget').value);save();$('profileDialog').close();render()};
$('calculateTarget').onclick=()=>{let p=u().profile,b=p.gender==='male'?10*p.weight+6.25*p.height-5*p.age+5:10*p.weight+6.25*p.height-5*p.age-161;$('calorieTarget').value=Math.round(b*num($('activity').value)+num($('goal').value))};
$('dishPreset').onchange=()=>{let option=$('dishPreset').selectedOptions[0];if(!option.dataset.cal)return;$('foodName').value=option.textContent;$('foodCalories').value=option.dataset.cal;$('foodProtein').value=option.dataset.p;$('foodCarbs').value=option.dataset.c;$('foodFat').value=option.dataset.f};
$('restaurantPreset').onchange=()=>{let value=$('restaurantPreset').value;if(!value)return;let [ri,di]=value.split(':').map(Number),dish=u().restaurants[ri].dishes[di];$('foodName').value=dish.name;$('foodCalories').value=dish.calories;$('foodProtein').value=dish.protein;$('foodCarbs').value=dish.carbs;$('foodFat').value=dish.fat};
$('manageRestaurants').onclick=()=>{refreshRestaurants();$('restaurantDialog').showModal()};
$('saveRestaurantDish').onclick=()=>{let name=$('restaurantName').value.trim(),dishName=$('restaurantDishName').value.trim(),calories=num($('restaurantDishCalories').value);if(!name||!dishName||!calories)return;let restaurant=u().restaurants.find(r=>r.name===name);if(!restaurant){restaurant={name,dishes:[]};u().restaurants.push(restaurant)}restaurant.dishes.push({name:dishName,calories,protein:num($('restaurantDishProtein').value),carbs:num($('restaurantDishCarbs').value),fat:num($('restaurantDishFat').value)});save();$('restaurantDishName').value='';$('restaurantDishCalories').value='';refreshRestaurants()};
$('searchSnack').onclick=async()=>{let query=$('snackSearch').value.trim(),button=$('searchSnack');if(!query){$('photoHelp').textContent='请先输入零食名称。';return}button.textContent='查询中…';button.disabled=true;try{let url=`https://world.openfoodfacts.org/cgi/search.pl?search_terms=${encodeURIComponent(query)}&search_simple=1&action=process&json=1&page_size=1`,data=await fetch(url).then(r=>r.json()),product=data.products?.[0],kcal=num(product?.nutriments?.['energy-kcal_100g']);if(!product||!kcal)throw Error('没有找到可用热量资料，请手动填写。');let grams=num($('snackGrams').value)||100;$('foodName').value=product.product_name||query;$('foodCalories').value=Math.round(kcal*grams/100);$('photoHelp').textContent=`已按 ${grams}g 计算；数据库标示为 ${kcal} kcal／100g，请核对包装标签。`}catch(error){$('photoHelp').textContent=error.message}finally{button.disabled=false;button.textContent='免费查询零食'}};
$('addFoodButton').onclick=()=>{editingIndex=null;$('foodForm').reset();document.querySelector('#foodDialog h2').textContent='添加餐食';$('foodDialog').showModal()};document.querySelectorAll('input[type="number"]').forEach(input=>{if(!['age','exerciseSteps','exerciseSets','exerciseReps'].includes(input.id))input.step='0.01'});
$('foodForm').onsubmit=e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();let f={name:$('foodName').value.trim(),type:$('mealType').value,calories:num($('foodCalories').value),protein:num($('foodProtein').value),carbs:num($('foodCarbs').value),fat:num($('foodFat').value),sodium:num($('foodSodium').value)},entries=[...today()];if(editingIndex===null)entries.push(f);else entries[editingIndex]=f;u().entries[day()]=entries;save();editingIndex=null;$('foodForm').reset();$('foodDialog').close();render()};
$('foodList').onclick=e=>{let card=e.target.closest('.food');if(card&&!e.target.closest('.delete'))editFood(Number(card.querySelector('.delete').dataset.index))};
$('weightForm').onsubmit=e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();let w=num($('dailyWeight').value);u().weights[day()]=w;u().profile.weight=w;save();$('weightDialog').close();render()};
function historyRow(date,previousWeight){let person=u(),foods=person.entries[date]||[],exercises=person.exercises[date]||[],hasWeight=Object.prototype.hasOwnProperty.call(person.weights||{},date),weight=hasWeight?num(person.weights[date]):null,intake=foods.reduce((sum,item)=>sum+num(item.calories),0),burned=exercises.reduce((sum,item)=>sum+num(item.calories),0),weightText=hasWeight?`${weight.toFixed(1)} kg${previousWeight===null?'':`（${weight-previousWeight>0?'+':''}${(weight-previousWeight).toFixed(1)}）`}`:'—';return {html:`<div class="history-item history-detail"><span><strong>${date}</strong><br>摄入 ${intake} kcal · 运动消耗 ${burned} kcal<br>体重 ${weightText}</span><strong>净摄入 ${intake-burned} kcal</strong></div>`,nextWeight:hasWeight?weight:previousWeight}}
$('historyButton').onclick=()=>{let person=u(),dates=[...new Set([...Object.keys(person.entries||{}),...Object.keys(person.weights||{}),...Object.keys(person.exercises||{})])].sort().slice(-548),previousWeight=null;let rows=dates.map(date=>{let row=historyRow(date,previousWeight);previousWeight=row.nextWeight;return row.html}).reverse();$('historyList').innerHTML=rows.length?rows.join(''):'<p class="muted">还没有历史记录。</p>';$('historyDialog').showModal()};
function renderInfo(){let q=$('infoSearch').value.trim(),items=nutritionInfo.filter(item=>item[0].includes(q)),guide=q?'':`<section class="guide"><h3>成年女性每日参考</h3>${femaleGuide.map(item=>`<div class="history-item"><span><strong>${item[0]}</strong> · ${item[1]}<br>${item[2]}</span></div>`).join('')}</section>`;$('infoList').innerHTML=guide+(items.map(item=>`<div class="history-item"><span><strong>${item[0]}</strong> · ${item[1]}<br>蛋白质 ${item[3]}g · 碳水 ${item[4]}g · 脂肪 ${item[5]}g</span><strong>${item[2]} kcal</strong></div>`).join('')||(!q?'':'<p class="muted">没有匹配项目。</p>'))}
$('infoButton').onclick=()=>{renderInfo();$('infoDialog').showModal()};$('infoSearch').oninput=renderInfo;
$('addExerciseButton').onclick=()=>{$('exerciseForm').reset();$('exerciseMinutes').value=30;$('exerciseDialog').showModal()};
$('exerciseType').onchange=()=>{let strength=['strength','weights'].includes($('exerciseType').value);$('exerciseMinutes').value=strength?'':30;$('exerciseMinutes').placeholder=strength?'选填':'30'};
$('exerciseForm').onsubmit=e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();let option=$('exerciseType').selectedOptions[0],type=$('exerciseType').value,minutes=num($('exerciseMinutes').value),steps=num($('exerciseSteps').value),met=num(option.dataset.met),part=$('strengthPart').value,name=$('exerciseName').value.trim()||(part?`${part} · ${option.textContent}`:option.textContent),calories=type==='walk'&&steps?Math.round(steps*.04):Math.round(met*3.5*u().profile.weight/200*minutes);let exercise={type,name,part,minutes,steps,sets:num($('exerciseSets').value),reps:num($('exerciseReps').value),weight:num($('exerciseWeight').value),calories};u().exercises[day()]=[...todayExercises(),exercise];save();$('exerciseDialog').close();render()};
const basicRender=render;render=()=>{basicRender();let gap=Math.max(0,Math.round(u().profile.weight*1.2-total('protein'))),p=document.createElement('p');p.className='photo-help';p.textContent=mealIdeas(num(u().profile.target)-total('calories'),gap);$('advice').append(p)};
const foodRender=render;render=()=>{foodRender();renderExercises()};
const appRender=render;render=()=>{appRender();document.querySelectorAll('.exercise-delete').forEach((button,index)=>{let item=todayExercises()[index],meta=button.closest('.food').querySelector('.food-meta');if(item.part)meta.textContent+=` · ${item.part}`;if(item.weight)meta.textContent+=` · ${item.weight}kg`});refreshRestaurants()};
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');trim();save();render();askWeight();
